### ISSUE TITLE
Push 1.1 to hackage

### ISSUE THREAD

**Issue by jonascarpay** [purenix-org/purenix#55]
As requested by @sternenseemann in https://github.com/purenix-org/purenix/commit/948e539b15f43d77e77ea0cace56f0625e14e9ea, and also just a good idea in general

**Comment by jonascarpay** [comment]
@cdepillabout I'm not authorized to push to hackage, can you take care of this?

**Comment by cdepillabout** [comment]
I've released `purenix-1.1` at the tip of current `main`: https://hackage.haskell.org/package/purenix-1.1

@jonascarpay I've added you as a maintainer on hackage, so you can now hopefully make releases.  Sorry about not doing that originally!

@sternenseemann Thanks for the heads up!
